classes: {
  red-dash: {
    style: {
      stroke: red
      stroke-width: 5
      animated: true
      stroke-dash: 6
    }
  }
  blue-dash: {
    style: {
      stroke: darkblue
      stroke-width: 4
      animated: true
      stroke-dash: 2
    }
  }
  green-dash: {
    style: {
      stroke: green
      stroke-width: 5
      animated: true
      stroke-dash: 3
    }
  }
  blue-bold: {
    style: {
      stroke: darkblue
      animated: true
      # stroke-dash: 6
      stroke-width: 9
    }
  }
  header: {
    style.underline: true
    style.font-size: 20
  }
}
